const fieldsModel = {
    pets: {
        dog: {
            race: [
                'Vira Lata (SRD)',
                'Affenpinscher',
                'Affenpinscher ',
                'Afghan Hound',
                'Aidi',
                'Airedale Terrier',
                'Akita Inu',
                'American Bully',
                'American Staffordshire Terrier',
                'Australian Cattle Dog',
                'Australian Shepherd',
                'Azawakh',
                'Barbet',
                'Basenji',
                'Basset Alpino',
                'Basset Artesiano Normando',
                'Basset Azul da Gasconha',
                'Basset de Vestfália',
                'Basset Hound',
                'Beagle',
                'Beagle Harrier',
                'Bearded Collie',
                'Bedlington Terrier',
                'Bernese Mountain Dog',
                'Bichon Bolonhês',
                'Bichon Frisé',
                'Bichon Havanês',
                'Biewer Terrier',
                'Billy',
                'Bloodhound',
                'Boerboel',
                'Boiadeiro de Appenzel',
                'Boiadeiro de Entlebuch',
                'Boiadeiro de Flandres',
                'Border Collie',
                'Border Terrier',
                'Borzói',
                'Boston Terrier',
                'Boxer',
                'Braco Alemão de Pêlo Curto',
                'Braco Alemão de Pêlo Duro',
                'Braco Alemão de Pêlo Longo',
                'Braco Austríaco de Pelo Liso',
                'Braco de Auvergne',
                'Braco de Bourbon',
                'Braco de Burgos',
                'Braco de Saint-germain',
                'Braco Dinamarquês',
                'Braco do Ariège',
                'Braco Eslovaco',
                'Braco Francês (Gascão E Pirenéus)',
                'Braco Húngaro',
                'Braco Italiano',
                'Braco Polonês',
                'Braco Tirolês',
                'Broholmer',
                'Buhund Norueguês',
                'Buldogue Campeiro',
                'Buldogue inglês',
                'Bull Terrier',
                'Bulldog',
                'Bulldog Francês',
                'Bullmastiff',
                'Cairn Terrier',
                'Cane Corso',
                'Cão Dágua Português',
                'Cão da Eurásia',
                'Cão da Groenlândia',
                'Cão da Islândia',
                'Cão da Serra da Estrela',
                'Cão da Serra da Estrela',
                'Cão de Artois',
                'Cão de Bestiar',
                'Cão de Caça Ao Cervo Sueco',
                'Cão de Canãa',
                'Cão de Castro Laboreiro',
                'Cão de Crista Chinês',
                'Cao de Guarda Holandês',
                'Cão de Lontra',
                'Cão de Pista de Sangue da Baviera',
                'Cão de Urso da Carélia',
                'Cão do Ariège',
                'Cão do Faraó',
                'Cão do Faraó',
                'Cão Dos Pirenéus',
                'Cão dos Pirineus',
                'Cão D’água Americano',
                'Cão D’água Espanhol',
                'Cão D’água Frison',
                'Cão D’água Irlandês',
                'Cão Finlandês da Lapônia',
                'Cão Lobo Checoslovaco',
                'Cão Lobo Checoslovaco',
                'Cão Lobo de Saarloos',
                'Cão Norueguês de Macareux',
                'Cão Tailandês de Crista Dorsal',
                'Cavalier King Charles Spaniel',
                'Chihuahua',
                'Chow Chow',
                'Cimarrón Uruguayo',
                'Cirneco do Etna',
                'Clumber',
                'Cocker Spaniel Americano',
                'Cocker Spaniel Inglês',
                'Collie',
                'Coonhound Preto E Castanho',
                'Coton de Tulear',
                'Dachshund',
                'Dachshund Pêlo Duro',
                'Dálmata',
                'Dandie Dinmont Terrier',
                'Doberman',
                'Dogo Argentino',
                'Dogue Alemão',
                'Dogue de Bordeaux',
                'Dogue do Tibete',
                'Dogue Maiorquino',
                'Drever',
                'Dunker Norueguês',
                'Elkhoud Norueguês',
                'Field Spaniel',
                'Fila Brasileiro',
                'Flat Coated Retriever',
                'Fox Terrier',
                'Foxhound Americano',
                'Foxhound Inglês',
                'Francês',
                'Fulvo da Bretanha de Pelô Duro',
                'Galgo Escocês',
                'Galgo Espanhol',
                'Galgo Húngaro',
                'Galgo Polonês',
                'Gascão Saintongeois',
                'Golden Retriever',
                'Grande Boiadeiro Suíço',
                'Greyhound',
                'Griffon de Bruxelas',
                'Grifo Belga,',
                'Grifo Bruxelense',
                'Grifo da Vendéia',
                'Grifo de Aponte de Pêlo Duro',
                'Grifo de Caça Checo',
                'Grifo Nivernais',
                'Halden Stovare',
                'Hamilton Stovare',
                'Hanover',
                'Harrier',
                'Hokkaïdo',
                'Hovawart',
                'Husky Siberiano',
                'Irish Glen Of Imaal Terrier',
                'Irish Soft Coated Wheaten Terrier',
                'Irish Wolfhound',
                'Jack Russell Terrier',
                'Kai',
                'Kelpie',
                'Kerry Blue Terrier',
                'King Charles Spaniel',
                'Kishu',
                'Komondor',
                'Korea Jindo Dog',
                'Kromfohrländer',
                'Kuvasz',
                'Labrador Retriever',
                'Lagotto Romagnolo',
                'Laika',
                'Lakeland Terrier',
                'Landseer',
                'Leonberger',
                'Lhasa Apso',
                'Malamute do Alasca',
                'Maltês',
                'Manchester Terrier',
                'Mastiff',
                'Mastim Dos Pirineus',
                'Mastim Espanhol',
                'Mastim Napolitano',
                'Mudi',
                'Norfolk Terrier',
                'Norwich Terrier',
                'Old English Sheepdog',
                'Papillon ',
                'Pastor',
                'Pastor Alemão',
                'Pastor Australiano',
                'Pastor Belga Groenendael',
                'Pastor Belga Malinois',
                'Pastor Belga Tervuren',
                'Pastor Bergamo',
                'Pastor branco suíço',
                'Pastor Catalão',
                'Pastor Croata',
                'Pastor da Anatólia',
                'Pastor da Ásia Central',
                'Pastor da Picardia',
                'Pastor da Rússia Meridional',
                'Pastor de Beauce',
                'Pastor de Brie',
                'Pastor de Shetland',
                'Pastor do Cáucaso',
                'Pastor Dos Pireneus',
                'Pastor Finlandês da Lapônia',
                'Pastor Holandês',
                'Pastor Iugoslavo',
                'Pastor Maremano Abruzês ',
                'Pastor Montanhês de Krast',
                'Pastor Polonês de Planície',
                'Pastor Polonês de Podhal',
                'Pastor Português da Serra de Aires',
                'Pelado Mexicano',
                'Pelado Peruano',
                'Pequeno Brabançon',
                'Pequeno Cão Holandês',
                'Pequeno Cão Leão',
                'Pequeno Cão Leão',
                'Pequeno Galgo Italiano',
                'Pequinês',
                'Perdigueiro Alemão',
                'Perdigueiro Português',
                'Pinscher',
                'Pinscher Austríaco',
                'Pitbull',
                'Podengo Ibicenco',
                'Podengo Português',
                'Pointer inglês',
                'Poitevin',
                'Poodle',
                'Porcelana',
                'Pudelpointer',
                'Pug',
                'Puli',
                'Pumi',
                'Rafeiro do Alentejo',
                'Retriever da Baía de Chesapeake',
                'Retriever da Nova Escócia',
                'Retriever de Pêlo Liso',
                'Retriever de Pêlo Ondulado',
                'Rodhesian Ridgeback ',
                'Rottweiler',
                'Sabujo Alemão',
                'Sabujo Anglo Francês',
                'Sabujo da Istria',
                'Sabujo da Transilvânia',
                'Sabujo de Hygen',
                'Sabujo de Posavatz',
                'Sabujo Eslovaco',
                'Sabujo Espanhol',
                'Sabujo Finlandês',
                'Sabujo Italiano',
                'Sabujo Iuguslavo',
                'Sabujo Suiço',
                'Saluki',
                'Samoieda',
                'São Bernardo',
                'Schapendoes',
                'Schiller Stovare',
                'Schipperke',
                'Schnauzer',
                'Scottish Terrier',
                'Sealyham Terrier',
                'Seter Inglês',
                'Setter Gordon',
                'Setter Irlandês',
                'SharPei',
                'Shiba',
                'Shih Tzu',
                'Silky Terrier Australiano',
                'Skye Terrier',
                'Sloughi',
                'Slovensky Cuvac',
                'Smäland Stovare',
                'Spaniel Azul da Picardia',
                'Spaniel Bretão',
                'Spaniel da Picardia',
                'Spaniel de Munster',
                'Spaniel de Pont-audemar',
                'Spaniel Francês',
                'Spaniel Japonês',
                'Spaniel Perdigueiro de Drenthe',
                'Spaniel Tibetano',
                'Spinone Italiano de Pêlo Duro',
                'Spitz Alemão',
                'Spitz Alemão Anão',
                'Spitz da Lapônia',
                'Spitz de Norboten',
                'Spitz Dos Visigodos',
                'Spitz Finlandês',
                'Spitz Japonês',
                'Springer Spaniel Gaulês',
                'Springer Spaniel Inglês',
                'Stabyhoun',
                'Staffordshire Bull Terrier',
                'Sussex Spanie',
                'Terra Nova',
                'TerraNova',
                'Terrier Alemão de Caça',
                'Terrier Australiano',
                'Terrier Brasileiro',
                'Terrier Checo',
                'Terrier Irlandês',
                'Terrier Japonês',
                'Terrier Miniatura Preto E Castanho',
                'Terrier Preto da Rússia',
                'Terrier Tibetano',
                'Tosa',
                'Vizsla Húngaro',
                'Vulpino Italiano',
                'Weimaraner',
                'Welsh Corgi Cardigan e Welsh Corgi Pembroke',
                'Welsh Terrier',
                'West Highland White Terrier',
                'Whippet',
                'Yakutian Laika',
                'Yorkshire Terrier',
            ],
            petFurColor: [
                'Branco',
                'Creme',
                'Caramelo',
                'Marrom',
                'Preto',
                'Malhado',
                'Pintado',
            ],
        },
        cat: {
            race: [
                'Sem Raça Definida (Vira Lata)',
                'Abissínio',
                'American Bobtail',
                'American Curl',
                'American Shorthair',
                'American Wirehair',
                'Angorá Turco',
                'Azul Russo',
                'Balinês',
                'Bengal',
                'Bombaim',
                'British Shorthair',
                'Burmês',
                'Burmila',
                'Califórnia Spangled',
                'Ceilão',
                'Chartreux',
                'Cornish Rex',
                'Cymric',
                'Devon Rex',
                'Europeu',
                'Exotic Shorthair',
                'Gato dos Bosques da Noruega',
                'German Rex',
                'Havana',
                'Himalaio',
                'Japanese Bobtail',
                'Javanês',
                'Korat',
                'Laperm',
                'Lince doméstico',
                'Maine Coon',
                'Manx',
                'Mau Egípcio',
                'Munchkin',
                'Ocicat',
                'Ojos azules',
                'Oriental',
                'Persa',
                'Pixie Bob',
                'Ragdoll',
                'Sagrado da Birmânia',
                'Scottish Fold',
                'Selkirk Rex',
                'Siamês',
                'Siberiano',
                'Singapura',
                'Snowshoe',
                'Sokoke',
                'Somali',
                'Sphynx',
                'Tonquinês',
                'Turco do Lago de Van',
                'York Chocolate',
            ],
            petFurColor: [
                'Branco',
                'Creme',
                'Caramelo',
                'Marrom',
                'Preto',
                'Malhado',
                'Pintado',
                'Rajado',
            ],
        },
        pet: {
            race: ['Escolha uma especie'],
            petFurColor: ['Escolha uma especie'],
        },
    },
};

module.exports = fieldsModel;
